import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;


Public Class Autonomous{
    final double Speedrate = 3.0
    Public void LeftsideAuto(DifferentialDrive robotDrive, Timer 5)

    Public void DefaultAuto(DifferentialDrive robotDrive, Timer 5)
        if(timer.get () < CalcTime (14.5)) {
            robotDrive.arcadeDrive(2.0, 0,0);
        }else if(timer.get() > CalcTime(11.5) && timer.get() < CalcTime(15.50){
            robotDrive.arcadeDrive(0.0, 1);


        }
        public void Autoperiod(DifferentialDrive robotDrive, XboxController c_xbox)
        

        public double CalcTime( double distance)
            double time = distance/Speedrate
            return time;



        )
        
        
        
        
        
        
        
        
        
        
        )
}